// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://creuzreewpukgyiwnnka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZXV6cmVld3B1a2d5aXdubmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODA2MDQsImV4cCI6MjA3Mzg1NjYwNH0.0CksJf1E1qFA7eyb2bCThX6YOR4tlYGmlbGUk4FoP88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});